
<div class="tab">
  <button class="tab-button active" id="shipping-taxes"><?php echo __('Estimate shipping & Taxes'); ?></button>
  <button class="tab-button" id="discount-code"><?php echo __('Discount Code'); ?></button>
  <button class="tab-button" id="gift-voucher"><?php echo __('Gift Voucher'); ?></button>
</div>
<?php echo $this->getLayout()->createBlock("Magento\Checkout\Block\Cart\Coupon")->setTemplate("Magento_Checkout::cart/coupon.phtml")->toHtml(); ?>

<?php if ($block->canShow()): ?>

<div class="cart-discount" style="display: none;">
  <div class="block discount" id="block-giftcard" data-mage-init='{"collapsible":{"openedState": "active", "saveState": false}}'>
    <div class="title" data-role="title">
        <strong id="block-discount-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Gift Cards'); ?></strong>
    </div>
    <div class="content" data-role="content" aria-labelledby="block-discount-heading">
            <form method="post" action="<?php echo $block->getUrl('mageworx_giftcards/cart/activateGiftCard'); ?>" id="activateGiftCard" novalidate="novalidate">
            <div class="fieldset giftcard">
              <div class="field">
                <label for="giftcard_code" class="label"><?php echo __('Redeem and use your Gift Card now'); ?></label>
                <div class="control">
                    <input type="text" value="" name="giftcard_code" id="giftcard_code" class="input-text" placeholder="<?php echo __('Redeem and use your Gift Card now');?>" >
                </div>
              </div>
              <div class="actions-toolbar">
                <div class="primary">
                  <button value="<?php echo __('Activate') ?>" class="action giftcards primary"
                        title="Activate" type="submit"><span><span><?php echo __('Activate') ?></span></span>
                  </button>
                </div>
              </div>
            </div>
            </form>

        <?php $currencySymbol = $block->getCurrencySymbol(); ?>
        <?php $temp = 0; ?>
        <?php if ($block->getSessionActive()) {
                    foreach($block->getFrontOptions() as $key => $value)
                    {
                        if ($temp) {
                            echo '<br/><br/>';
                        }
                        echo '<b>'. $this->helper('Magento\Checkout\Helper\Data')->formatPrice($value['applied']).' '.__('applied from Gift Card').' '.$value['code'].'.</b><br/>';
                        echo __('Remaining card balance').': '. $this->helper('Magento\Checkout\Helper\Data')->formatPrice($value['remaining']).'. (<a href="'.$block->getUrl("mageworx_giftcards/cart/deActivateGiftCard/id/$key").'">'.__('Remove').'</a>)';
                        $temp = 1;
                    }
              }
        ?>
    </div>
  </div>
</div>

<?php endif; ?>

<script type="text/javascript">
    require(["jquery"], function($){
        jQuery("#block-discount").hide();
        jQuery('body').on("click","#shipping-taxes",function(){
            jQuery(".tab-button").removeClass('active');
            jQuery(this).addClass('active');
            jQuery("#block-shipping").show();
            jQuery("#block-discount").hide();
            jQuery(".cart-discount").hide();
        });
        jQuery('body').on("click","#discount-code",function(){
            jQuery(".tab-button").removeClass('active');
            jQuery(this).addClass('active');
            jQuery("#block-shipping").hide();
            jQuery("#block-discount").show();
            jQuery(".cart-discount").hide();
        });
        jQuery('body').on("click","#gift-voucher",function(){
            jQuery(".tab-button").removeClass('active');
            jQuery(this).addClass('active');
            jQuery("#block-shipping").hide();
            jQuery("#block-discount").hide();
            jQuery(".cart-discount").show();
        });

    });
</script>