
<div class="mpblog-search">
<svg xmlns="http://www.w3.org/2000/svg" style="display:none">
  <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-search-13" viewBox="0 0 40 40">
    <path d="M26.804 29.01c-2.832 2.34-6.465 3.746-10.426 3.746C7.333 32.756 0 25.424 0 16.378 0 7.333 7.333 0 16.378 0c9.046 0 16.378 7.333 16.378 16.378 0 3.96-1.406 7.594-3.746 10.426l10.534 10.534c.607.607.61 1.59-.004 2.202-.61.61-1.597.61-2.202.004L26.804 29.01zm-10.426.627c7.323 0 13.26-5.936 13.26-13.26 0-7.32-5.937-13.257-13.26-13.257C9.056 3.12 3.12 9.056 3.12 16.378c0 7.323 5.936 13.26 13.258 13.26z"
    fill-rule="evenodd" />
  </symbol>
  <symbol xmlns="http://www.w3.org/2000/svg" id="sbx-icon-clear-3" viewBox="0 0 20 20">
    <path d="M8.114 10L.944 2.83 0 1.885 1.886 0l.943.943L10 8.113l7.17-7.17.944-.943L20 1.886l-.943.943-7.17 7.17 7.17 7.17.943.944L18.114 20l-.943-.943-7.17-7.17-7.17 7.17-.944.943L0 18.114l.943-.943L8.113 10z" fill-rule="evenodd" />
  </symbol>
</svg>

<div class="searchbox sbx-google">
  <div role="search" class="sbx-google__wrapper">
    <input name="search" placeholder="Search your website" autocomplete="off" required="required" class="sbx-google__input" type="search">
    <button type="submit" title="Submit your search query." class="sbx-google__submit">
      <svg role="img" aria-label="Search">
        <use xlink:href="#sbx-icon-search-13"></use>
      </svg>
    </button>
    <button type="reset" title="Clear the search query." class="sbx-google__reset">
      <svg role="img" aria-label="Reset">
        <use xlink:href="#sbx-icon-clear-3"></use>
      </svg>
    </button>
  </div>
    <!-- <div class="block block-content">
        <div class="field search">
            <label class="label" for="mpblog-search-box" data-role="minisearch-label">
                <span><?php echo __('Search'); ?></span>
            </label>
            <div class="control">
                <input id="mpblog-search-box"
                       type="text"
                       name="query"
                       value="<?php echo $this->getRequest()->getParam('query') ?>"
                       placeholder="<?php echo __('Search blogs here...'); ?>"
                       class="input-text"
                       role="combobox"
                       aria-haspopup="false"
                       aria-autocomplete="both"
                       />
            </div>
        </div>
        <div class="actions">
            <button type="submit"
                    title="<?php echo __('Search') ?>"
                    class="action search">
                <i class="fa fa-search" aria-hidden="true" style="font-size: 16px;margin-top: 5px;"></i>
            </button>
        </div>
    </div> -->
</div>

<script>
    require([
        'jquery',
        'autocomplete'
    ], function ($) {
        var visibleImage = <?php echo $block->getSidebarConfig('search/show_image'); ?>;
        $('#mpblog-search-box').autocomplete({
            lookup: <?php echo $block->getSearchBlogData();?>,
            lookupLimit: <?php echo $block->getSidebarConfig('search/search_limit') ?: 10; ?>,
            maxHeight: 2000,
            minChars: <?php echo $block->getSidebarConfig('search/min_chars') ?: 1; ?>,
            onSelect: function (suggestion) {
                var urlString = suggestion.url;
                window.location.href = urlString.substring(0,urlString.length - 1);
            },
            formatResult: function (suggestion, currentValue) {
                var urlString = suggestion.url;
                var html = "<a class='mpblog-suggestion' href='" + urlString.substring(0,urlString.length - 1) + "'>";
                if (visibleImage) {
                    html += "<div class='mpblog-suggestion-left'><img class='img-responsive' src='" + suggestion.image + "' /></div>"
                }
                html += "<div class='mpblog-suggestion-right'>" +
                    "<div class='mpblog-product-line mpblog-product-name'>" + suggestion.value + "</div>" +
                    "<div class='mpblog-product-des'><p class='mpblog-short-des'>" + suggestion.desc + "</p></div></div></a>";

                return html;
            }
        });
    });
</script>
