<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php /** @var \Amasty\Storelocator\Block\Location $block */ ?>
<section class="business social_bannerarea">
	
	<img src="<?php echo $this->getViewFileUrl('Amasty_Storelocator::images/background.jpg'); ?>" alt="Amasty_Storelocator" />
	<div class="container">
		<div class="table_box_area">
			<div class="table_box_inner">
				<div class="bushead">
					<h1>Where to find cucina & Amore</h1>
				</div>
			</div>
		</div>
	</div>
</section>

<div class="amlocator_center" style="padding-top:30px">
	<h2><?php echo "PLease check the below direction from your location";?></h2>
    <div class="col-md-12">
		<div id="directions" class="col-md-3"></div>
		<div id="amlocator-map-canvas" style="width:75%;"></div>
	</div>
</div>

<script>
    var baloonTemplate = <?php echo $block->getBaloonTemplate() ?>;
    var amMediaUrl = "<?php echo $block->getAmStoreMediaUrl() ?>";
</script>
<?php 
$id = $this->getRequest()->getParam("id");
$lat = $this->getRequest()->getParam("lat");
$lng = $this->getRequest()->getParam("lng");
if($id){
    $om = \Magento\Framework\App\ObjectManager::getInstance();
    $storeManager = $om->get('Magento\Store\Model\StoreManagerInterface');

    if($id!=''){
        $data = $this->helper('Amasty\Storelocator\Helper\Detail')->getStoreInfo($id);
		//echo '<pre>';print_r($data);echo '</pre>';
    }
}
?>

<script language="javascript" type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true&libraries=places<?php echo $block->getApiKey() ?>"></script>
<script type="text/javascript">
  var directionDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;

  function initialize() {
    directionsDisplay = new google.maps.DirectionsRenderer();
    var myOptions = {
      mapTypeId: google.maps.MapTypeId.ROADMAP,
    }
    map = new google.maps.Map(document.getElementById("amlocator-map-canvas"), myOptions);
    directionsDisplay.setMap(map);

    var start = '<?php echo $lat; ?>, <?php echo $lng; ?>';
    var end = '<?php echo $data['lat']; ?>, <?php echo $data['lng']; ?>';
    var request = {
      origin:start, 
      destination:end,
      travelMode: google.maps.DirectionsTravelMode.DRIVING
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
        var myRoute = response.routes[0];
        var txtDir = '';
        for (var i=0; i<myRoute.legs[0].steps.length; i++) {
          txtDir += myRoute.legs[0].steps[i].instructions+"<br />";
        }
		document.getElementById('directions').innerHTML = txtDir;
        
      }else{
		alert("Sorry, There is not roadmap available for this location");
		window.location = "<?php echo $block->getUrl('amlocator'); ?>";
	  }
    });
  }

initialize();
</script>