<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Storelocator
 */
?>
<?php

/** @var $block \Amasty\Storelocator\Block\Adminhtml\Attribute\Edit\Tab\Option\Field */

$stores = $block->getStoresSortedBySortOrder();
?>

    <div id="manage-options-panel" data-index="attribute_options_select_container">
        <table class="admin__control-table" data-index="attribute_options_select">
            <thead>
            <tr id="attribute-options-table">
                <th class="col-draggable"></th>
                <th class="col-default control-table-actions-th"><span><?php /* @escapeNotVerified */ echo __('Is Default') ?></span></th>
                <?php
                foreach ($stores as $_store): ?>
                    <th<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> class="_required"<?php endif; ?>>
                        <span><?php /* @escapeNotVerified */ echo __($_store->getName()) ?></span>
                    </th>
                <?php endforeach;
                $storetotal = count($stores) + 3;
                ?>
                <th class="col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?php /* @escapeNotVerified */ echo $storetotal; ?>" class="validation">
                    <input type="hidden" class="required-dropdown-attribute-entry" name="dropdown_attribute_validation"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?php /* @escapeNotVerified */ echo $storetotal; ?>" class="col-actions-add">
                    <button id="add_new_option_button" data-action="add_new_row" title="<?php /* @escapeNotVerified */ echo __('Add Option'); ?>"
                            type="button" class="action- scalable add">
                        <span><?php /* @escapeNotVerified */ echo __('Add Option'); ?></span>
                    </button>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="option-count-check" value="" />
    </div>
    <script id="row-template" type="text/x-magento-template">
        <tr>
            <td class="col-draggable">
                <div data-role="draggable-handle" class="draggable-handle" title="<?php /* @escapeNotVerified */ echo __('Sort Option'); ?>"></div>
                <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>" />
            </td>
            <td class="col-default control-table-actions-cell">
                <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %>/>
            </td>
            <?php foreach ($stores as $_store): ?>
                <td class="col-<%- data.id %>"><input name="option[value][<%- data.id %>][<?php /* @escapeNotVerified */ echo $_store->getId() ?>]" value="<%- data.store<?php /* @escapeNotVerified */ echo $_store->getId() ?> %>" class="input-text<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option<?php endif; ?>" type="text" /></td>
            <?php endforeach; ?>
            <td id="delete_button_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                <button id="delete_button_<%- data.id %>" title="<?php /* @escapeNotVerified */ echo __('Delete') ?>" type="button"
                        class="action- scalable delete delete-option"
                >
                    <span><?php /* @escapeNotVerified */ echo __('Delete') ?></span>
                </button>
            </td>
        </tr>
    </script>
    <?php
    $values = [];
    $options = $block->getOptionValues();
    if ($options) {
        foreach($options as $value) {
            $value = $value->getData();
            $values[] = is_array($value) ? array_map("htmlspecialchars_decode", $value) : $value;
        }
    }
    ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_Catalog/js/options": {
                    "attributesData": <?php /* @noEscape */ echo json_encode($values, JSON_HEX_QUOT); ?>,
                    "isSortable":  0
                }
            }
        }
    </script>

<script>
    require([
        'jquery'
    ], function (jquery) {
        var initialized = false;

        function init(){
            if (!initialized) {
                jquery('#manage-options-panel').trigger('render');

                jquery('[data-role=options-container]').sortable({cancel: 'select, input, button'});
            }
        }
        setTimeout(init, 1000);
    });
</script>

