<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper('Magento\Search\Helper\Data');
$rand = rand(5, 1500);
?>
<div class="block block-search">
    <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
    <div class="block block-content">
		<span class="search-button"><i class="ion-ios-search"></i></span>
        <form class="form minisearch" id="search_mini_form_<?php echo $rand; ?>" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
			<div class="input-group">
			   <input id="search_<?php echo $rand; ?>"
				   data-mage-init='{"quickSearch":{
						"formSelector":"#search_mini_form_<?php echo $rand; ?>",
						"url":"<?php /* @escapeNotVerified */ echo $block->getUrl('search/ajax/suggest', ['_secure' => $block->getRequest()->isSecure()]); ?>",
						"destinationSelector":"#search_autocomplete_<?php echo $rand; ?>"}
				   }'
				   type="text"
				   name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
				   value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
				   placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
				   class="form-control"
				   maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
				   role="combobox"
				   aria-haspopup="false"
				   aria-expanded="true"
				   aria-autocomplete="both"
				   autocomplete="off"/>
				<span class="input-group-btn">
					<button type="submit"
							title="<?php echo $block->escapeHtml(__('Search')) ?>"
							class="action btn btn-default">
						<span><i class="fa fa-search"></i></span>
					</button>
				</span>
				<div id="search_autocomplete_<?php echo $rand; ?>" class="search-autocomplete"></div>
			</div>
			<?php echo $block->getChildHtml() ?>
        </form>
    </div>
</div>


