<form class="" method="post" action="#">
					<div class="form-group head_form">
						<div class="cols-sm-12">
							<div class="input-group">
								<input type="password" class="form-control" id="InputPassword" placeholder="Enter business password">
							</div>
						</div>
					</div>
					<div class="form-group">
						<a href="" target="_blank" type="button" id="button" class="btn btn-primary btn-lg btn-block submit-button">Submit</a>
					</div>
				</form>