<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog post list item template
 *
 * @var $block \Magefan\Blog\Block\Post\AbstractPost
 */
?>
<?php
$_post = $this->getPost();
$_postUrl = $_post->getPostUrl();
$_postName = $block->escapeHtml($_post->getTitle(), null, true);
$_postDate = $_post->getData("publish_time");
?>
<div class="col-md-6 post-holder-<?php echo $_post->getId() ?>">
    <div class="post-header">
        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
            <div class="post-ftimg-hld">
                <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_postName ?>" />
                </a>
            </div>
        <?php } ?>
        <div class="post-title-holder">
            <h2 class="post-title">
                <a class="post-item-link"
                   href="<?php echo $_postUrl ?>">
                       <?php echo $_postName; ?>
                </a>
            </h2>
        </div>
    </div>
    <div class="post-content">
        <div class="post-description clearfix">
            <div class="post-text-hld clearfix">
                <?php echo $block->getShorContent() ?>
            </div>         
        </div>
    </div>
    <div class="post-footer">
        <?php echo $this->getInfoHtml() ?>
        <a class="btn btn-default post-read-more" href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>"><?php echo __('Read more') ?></a>
    </div>
</div>