<section class="headoffice">
	 <div class="container">
		<div class="new_head">
			 <center>
				<h2 style="padding-bottom:30px;">Existing Business Customer Service Center</h2>
				<hr></br></br>
				<form class="" method="post" action="<?php echo $block->getUrl('business-customers/enquiry/send'); ?>">
					<div class="form-group head_form">
						<div class="cols-sm-12">
							<div class="input-group">
								<input type="text" class="form-control" id="email_id" placeholder="Enter your Email" name="email">
							</div>
						</div>
					</div>
					<div class="form-group">
						<input type="submit" class="btn btn-primary btn-lg btn-block submit-button" value="Submit" >
					</div>
				</form>
			</center>
		</div>
	</div>	
</section>	