<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar archive template
 *
 */
?>
<div class="widget block block-instagram" data-bind="scope: 'blog-instagram'">
    <div class="block-title">
        TEST
    </div>
</div>