<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog sidebar recent posts template
 *
 * @var $block \Magefan\Blog\Block\Sidebar\Recent
 */
?>

<?php
$_postCollection = $block->getPopularPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
    <div class="widget block block-recent-post" data-bind="scope: 'recemt-posts'">
        <div class="block-title"><?php echo __('Popular Recipe') ?></div>
        <div class="block-content">
            <ul class="list-inline">
                <?php foreach ($_postCollection as $_post) { ?>
                    <li class="clearfix">
                        <?php if ($post_image = $_post->getFeaturedImage()): ?>
                            <div class="post-image">
                                <img src="<?php echo $post_image; ?>" alt=""/>
                            </div>
                        <?php endif; ?>
                        <a class="post-item-link"
                           href="<?php echo $_post->getPostUrl() ?>">
                               <?php echo $block->escapeHtml($_post->getTitle()) ?>
                        </a>
                        <div class="post-info clear">
                            <?php if ($_author = $_post->getAuthor()) { ?>            
                                <div class="item post-author">
                                    <span class="label"><?php echo __('By') ?></span>
                                    <span class="value">
                                        <?php echo $block->escapeHtml($_author->getTitle()) ?>
                                    </span>
                                    <span class="dash">/</span>
                                </div>            
                            <?php } ?>
                            <div class="item post-posed-date">
                                <span class="value"><?php echo $_post->getPublishDate('F d, Y') ?></span>
                            </div>
                        </div>
                    </li>

                <?php } ?>
            </ul>
        </div>
    </div>
<?php } ?>