<?php
$posts        = $block->getBlogPagination();
$resizeWidth  = $block->getBlogConfig('general/resize_image/resize_width');
$resizeHeight = $block->getBlogConfig('general/resize_image/resize_height');
$currentPage  = $block->getPageParam();
if ($currentPage == null) {
	$currentPage = 1;
}
?>
<?php echo $this->getChildHtml("top_banner"); ?>

<div class="container">
<?php if ($posts != '') : ?>
	<?php
	$countPage = $posts[0];
	array_shift($posts);
	?>
    <div class="post-list-container mpcss" id="mpblog-list-container">
        <div class="row">
            <?php if ($block->getBlogConfig('sidebar/sidebar_left_right') == 1) {
				?>

                <div class="post-list-content col-md-9 col-sm-8 col-xs-12">
					<?php echo $this->getChildHtml('sidebar_search'); ?>
                    <div class="post-list-body">
                <?php foreach ($posts as $post) : ?>
                    <div class="post-list-item <?php if ($block->getBlogConfig('general/display_style') == 2) {
						echo ' col-sm-6';
					} else echo ' col-sm-12'; ?>">
                        <div class="post-item-wraper">
                            <div class="post-image">
                                <?php if ($post->getImage()) :
                                    ?>
                                    <a href="<?php echo substr($block->getUrlByPost($post), 0, -1) ?>">
                                        <img class="img-responsive"
                                             src="<?php echo $block->resizeImage($post->getImage(), $resizeWidth, $resizeHeight); ?>"
                                             alt="<?php echo $block->escapeHtml($post->getName()); ?>"/>
                                    </a>
								<?php endif; ?>
                            </div>
                            <div class="post-info-wraper">
                                <h3 class="mp-post-title">
                                    <a class="post-link-title" title="<?php echo $post->getName(); ?>"
                                       href="<?php echo substr($block->getUrlByPost($post), 0, -1) ?>">
                                        <?php echo $post->getName(); ?>
                                    </a>
                                </h3>

                                <div class="post-short-description">
                                    <p><?php echo $post->getShortDescription(); ?></p>
                                </div>

                                <div class="mp-clearfix"></div>

                                <div class="mp-post-meta-info mp-alignright">
									<div class="actions">
										<a class="mp-read-more" href="<?php echo substr($block->getUrlByPost($post), 0, -1); ?>"
										   title="<?php echo __('Read More'); ?>"><?php echo __('Read more'); ?></a>
									</div>
									<div class="views pull-right">
										<p>
											<span>
												By <?php echo $block->getAuthorByPost($post->getAuthorId())->getName(); ?>
												/ <?php echo $block->getPostCategoryHtml($post) ;?>
												/ <?php echo $this->getViewCount($post->getPostId()); ?> Views 
											</span>
										</p>
									</div>
                                </div>
                            </div>
                        </div>
                    </div>
				<?php endforeach; ?>
                </div>
            </div>

                <div class="mp-sidebar col-md-3 col-sm-4 col-xs-12">

                <?php
				//echo $this->getChildHtml('sidebar_search');
				echo $this->getChildHtml('mpblog_sidebarcategory');
				echo $this->getChildHtml('mpblog_sidebarmostview');
				
				//echo $this->getChildHtml('mpblog_sidebarmonthly');
				//echo $this->getChildHtml('mpblog_sidebartopic');
				//echo $this->getChildHtml('mpblog_sidebartag');
				?>

            </div>
				<?php
			} else { ?>

                <div class="mp-sidebar col-md-3 col-sm-4 col-xs-12">
                    <?php
					//echo $this->getChildHtml('sidebar_search');
					echo $this->getChildHtml('mpblog_sidebarcategory');
					echo $this->getChildHtml('mpblog_sidebarmostview');
					
					//echo $this->getChildHtml('mpblog_sidebarmonthly');
					//echo $this->getChildHtml('mpblog_sidebartopic');
					//echo $this->getChildHtml('mpblog_sidebartag');
					?>
                </div>

                <div class="post-list-content col-md-9 col-sm-8 col-xs-12">
                    <div class="post-list-body">
                <?php foreach ($posts as $post) : ?>
                    <div class="post-list-item <?php if ($block->getBlogConfig('general/display_style') == 2) {
						echo ' col-sm-6';
					} else echo ' col-sm-12'; ?>">
                        <div class="post-item-wraper">
                            <div class="post-image">
                                <?php if ($post->getImage()) : ?>
                                    <a href="<?php echo substr($block->getUrlByPost($post), 0, -1) ?>">
                                        <img class="img-responsive"
                                             src="<?php echo $block->resizeImage($post->getImage(), $resizeWidth, $resizeHeight); ?>"
                                             alt="<?php echo $block->escapeHtml($post->getName()); ?>"/>
                                    </a>
								<?php endif; ?>
                            </div>
                            <div class="post-info-wraper">
                                <h2 class="mp-post-title">
                                    <a class="post-link-title" title="<?php echo $post->getName(); ?>"
                                       href="<?php echo substr($block->getUrlByPost($post), 0, -1) ?>">
                                        <?php echo $post->getName(); ?>
                                    </a>
                                </h2>

                                <div class="mp-post-info">
                                    <?php echo __('Posted on ') . $block->getDateFormat($post->getPublishDate()); ?>
									<?php
									echo ($block->getPostCategoryHtml($post)) ? __('| Posted in ') . $block->getPostCategoryHtml($post) : ('');
									?>
									<?php

									if ($block->getAuthorByPost($post->getAuthorId())->getName() && $block->getBlogConfig('general/display_author')) { ?>
                                        | By :
                                        <a class="mp-info" href="<?php echo $block->getAuthorUrl($block->getAuthorByPost($post->getAuthorId())) ?>"><?php echo $block->getAuthorByPost($post->getAuthorId())->getName(); ?></a>
									<?php } ?>
                                </div>


                                <div class="post-short-description">
                                    <p><?php echo $post->getShortDescription(); ?></p>[...]
                                </div>

                                <div class="mp-clearfix"></div>

                                <div class="mp-post-meta-info mp-alignright">
                                        <div class="actions">
                                            <a class="mp-read-more" href="<?php echo substr($block->getUrlByPost($post), 0, -1); ?>"
                                               title="<?php echo __('Read More'); ?>"><?php echo __('Read more'); ?></a>
                                        </div>
                                </div>
                            </div>
                        </div>
                    </div>
				<?php endforeach; ?>
                </div>
            </div>

			<?php } ?>
        </div>
    </div>

	<?php if ($countPage > 1): ?>
        <ul class="items mp-blog-pages" aria-labelledby="paging-label">
        <?php
		$end         = floor($countPage);
		$relatedPage = $currentPage - 2;
		if ($relatedPage <= 0) {
			$relatedPage = 1;
		}
		?>

		<?php echo $block->getPrevPage($currentPage); ?>
		<?php echo $block->getFirstPage($currentPage); ?>

		<?php
		for ($i = 1; $i <= 5; $i++) {
			echo $block->getAllPage($currentPage, $relatedPage, $i);
			if ($relatedPage == $end) {
				break;
			}
			$relatedPage = $relatedPage + 1;
		}
		?>
		<?php
		if ($relatedPage < $end){
			echo $block->getLastPage($currentPage, $end);

		}
		echo $block->getNextPage($currentPage, $end);
		?>

        </ul>
	<?php endif; ?>

<?php else : ?>

    <div class="post-list-container mpcss">
        <div class="row">
              <?php if ($block->getBlogConfig('sidebar/sidebar_left_right') == 1) {
				  ?>
                  <div class="post-list-content col-md-9 col-sm-8 col-xs-12">
                  <?php echo __('There are no posts at this moment'); ?>
            </div>
                  <div class="mp-sidebar col-md-3 col-sm-4 col-xs-12">
                <?php
				echo $this->getChildHtml('sidebar_search');
				echo $this->getChildHtml('mpblog_sidebarmostview');
				echo $this->getChildHtml('mpblog_sidebarcategory');
				echo $this->getChildHtml('mpblog_sidebarmonthly');
				echo $this->getChildHtml('mpblog_sidebartopic');
				echo $this->getChildHtml('mpblog_sidebartag');
				?>
            </div>
			  <?php } else { ?>
                  <div class="mp-sidebar col-md-3 col-sm-4 col-xs-12">
                        <?php
						echo $this->getChildHtml('sidebar_search');
						echo $this->getChildHtml('mpblog_sidebarmostview');
						echo $this->getChildHtml('mpblog_sidebarcategory');
						echo $this->getChildHtml('mpblog_sidebarmonthly');
						echo $this->getChildHtml('mpblog_sidebartopic');
						echo $this->getChildHtml('mpblog_sidebartag');
						?>
                    </div>

                  <div class="post-list-content col-md-9 col-sm-8 col-xs-12">
                        <?php echo __('There are no posts at this moment'); ?>
                    </div>
			  <?php } ?>
        </div>

    </div>

<?php endif; ?>

<script>
    require([
        'jquery',
        'Mageplaza_Blog/js/lib/less.min'
    ], function ($) {
        $(document).ready(function () {
            $("#popular-tab").click(function () {
                $("#recent-tab").css("display", "block");
            });
            $("#recent-tab").click(function () {
                $("#popular-tab").css("display", "block");
            });
        });
    });
</script>
</div>