<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php $url = $block->getReviewsUrl() . '#reviews'; ?>
<?php $urlForm = $block->getReviewsUrl() . '#review-form'; ?>
<?php if ($block->getReviewsCount()): ?>
<?php $rating = $block->getRatingSummary(); ?>
<div class="product-reviews-summary<?php echo !$rating ? ' no-rating' : ''?>" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
    <?php if ($rating):?>
    <div class="rating-summary">
         <span class="label"><span><?php /* @escapeNotVerified */ echo __('Rating') ?>:</span></span>
         <div class="rating-result" title="<?php /* @escapeNotVerified */ echo $rating; ?>%">
             <span style="width:<?php /* @escapeNotVerified */ echo $rating; ?>%"><span><span itemprop="ratingValue"><?php /* @escapeNotVerified */ echo $rating; ?></span>% of <span itemprop="bestRating">100</span></span></span>
         </div>
     </div>
    <?php endif;?>
    <div class="reviews-actions">
        <a class="action view" href="<?php /* @escapeNotVerified */ echo $url ?>"><span itemprop="reviewCount"><?php /* @escapeNotVerified */ echo $block->getReviewsCount() ?></span>&nbsp;<span><?php /* @escapeNotVerified */ echo($block->getReviewsCount() == 1) ? __('Review') : __('Reviews') ?></span></a>
        <!--<a class="action add" href="<?php /* @escapeNotVerified */ echo $urlForm ?>"><?php /* @escapeNotVerified */ echo __('Add Your Review') ?></a>-->
		 <a class="action add review-trigger" href="javascript:void(0)"><?php /* @escapeNotVerified */ echo __('Add Your Review') ?></a>
    </div>
</div>
<?php elseif ($block->getDisplayIfEmpty()): ?>
<div class="product-reviews-summary empty">
    <div class="reviews-actions">
        <!--a class="action add" href="<?php /* @escapeNotVerified */ //echo $urlForm; ?>">
            <?php /* @escapeNotVerified */ //echo __('Be the first to review this product') ?>
        </a-->
		<a class="action add review-trigger" href="javascript:void(0)">
            <?php /* @escapeNotVerified */ echo __('add review') ?>
        </a>
		
    </div>
</div>
<?php endif; ?>
	<script>
	require(['jquery'],function($p){
		    $p(function(){
				 $p('.review-trigger').on('click', function(){
					 $p('.review-form').show();
					 // $p('.review-form').addClass('active');
					 //$p('body').addClass('review-open');
				});
				 $p('.btn-trigger').on('click', function(){
						$p('.review-form').removeClass('active');
						$p('.review-form').hide();
				});
				 $p('.review-trigger-close').on('click', function(){
					 $p('.review-form').removeClass('active');
					 $p('.review-form').hide();
					 $p('body').removeClass('review-open');
				});
			});
	 });
	</script>
	<div class="review-form1" style="display:none;">
		<span class="form-layer"></span>
		<div class="insd-review-form">
			<a href="javascript:void(0)" class="close-pop review-trigger-close"></a>
			<p>gsdfhsdjghjsdfg
			sdhghsdfkhgjkdfhgdf
			sdfhdfjkghdfjghfkghdfkg
			hjkdfhgjkdfhgkdjfhgjkdfhg
			dshgjkdfhgjdfhgjkdfhgdfjkg
			'dfhgjdfhgjkdfhgjkdfghdfjkghdf
			dfhgjdfhgjkdfhgjdfhgdfjhgdf
			'dfhgjkdfhgjdfhgldfhg</p>
			
		</div> 
	</div>
						