<?php
/**
 * Copyright © 2015 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog related posts template
 *
 * @var $block \Magefan\Blog\Block\Post\View\RelatedPosts
 */
?>

<?php if ($block->displayPosts()) { ?>
    <?php $_postCollection = $block->getPostCollection(); ?>
    <?php if ($_postCollection->count()) { ?>
        <div class="block related">
            <div class="block-title title">
                <strong id="block-relatedposts-heading" role="heading" aria-level="2">
                    <?php echo __('Related Posts') ?>
                </strong>
            </div>
            <div class="row block-content">
                <?php foreach ($_postCollection as $_post) { ?>
                    <div class="col-md-6 item">
                        <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                            <div class="post-ftimg-hld">
                                <a href="<?php echo $_post->getPostUrl() ?>" title="<?php echo $_post->getTitle(); ?>">
                                    <img src="<?php echo $featuredImage ?>" alt="<?php echo $_post->getTitle(); ?>" />
                                </a>
                            </div>
                        <?php } ?>                        
                        <a class="post-item-link"
                           href="<?php echo $_post->getPostUrl() ?>">
                               <?php echo $block->escapeHtml($_post->getTitle()); ?>
                        </a>
                        <div class="post-text-hld clearfix">
                            <?php 							
							$content=strip_tags($_post->getShortFilteredContent());
							if(strlen($content) > 80){
							$pos=strpos($content, ' ', 80);
							echo substr($content,0,$pos ).'...'; 
							}else{
								echo $_post->getShortFilteredContent();
							}								
							?>
                        </div> 
                        <a class="btn post-read-more" href="<?php echo $_post->getPostUrl() ?>" title="<?php echo $_post->getTitle(); ?>"><?php echo __('Read more') ?></a>
                    </div>
                <?php } ?>
            </div>
        </div>
    <?php } ?>
<?php } ?>